server:
  port: 8085
spring:
  data:
    mongodb:
      username: user
      password: password
      host: localhost
      port: 27017
      database: extern-db
      authentication-database: admin
  webflux:
    base-path: tarom